# Generated by Django 5.1.3 on 2024-12-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0002_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
